A lot of this stuff hinges on having the right initial data. We cant run the agents at this moment. I Added the stuff here that was already in workshop 4, but like I said, it will not run.

Personally, I believe that we have to store the eventual data of every script in a csv file. This script needs a program of requirements.

Load Libraries

In [1]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import pandas as pd
import numpy as np
import functions
np.random.seed(0)

Define Stencil

In [2]:
# creating neighborhood definition
stencil = tg.create_stencil("von_neumann", 1, 1)
# setting the center to zero
stencil.set_index([0,0,0], 0)
print(stencil)

[[[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 1 0]
  [1 0 1]
  [0 1 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]]


Define the environment

In [3]:
# loading the lattice from csv
lattice_path = os.path.relpath('../data/meshes/voxelized_envelope_highres.csv')
avail_lattice = tg.lattice_from_csv(lattice_path)
init_avail_lattice = tg.to_lattice(np.copy(avail_lattice), avail_lattice)

load program (insert the program of requirements here)

In [4]:
#loading the relative relations excell

# relative_rels = pd.read_excel('../data/relationships/relative_relations.xlsx', index_col=0) 
# relative_rels_norm = relative_rels.div(relative_rels.sum(axis=1), axis=0)
# relative_rels_norm = relative_rels_norm.fillna(0)

#loading the relative preferences excell
relative_prefs = pd.read_excel('../data/relationships/relative_preferences.xlsx')
relative_prefs.iloc[:, 1:] = relative_prefs.iloc[:, 1:].div(relative_prefs.iloc[:, 1:].sum(axis=1), axis=0)
relative_prefs.iloc[:, 1:] = relative_prefs.iloc[:, 1:].fillna(0)
relative_prefs_norm = relative_prefs
# relative_prefs_norm = relative_prefs_norm.head(3)

In [5]:
program_prefs = relative_prefs_norm.drop(["space_name"], 1)
program_prefs

sunlight_access  noise_approval  proximity_to_ground_floor  \
0          0.227273        0.181818                   0.000000   
1          0.256410        0.230769                   0.256410   
2          0.204082        0.183673                   0.000000   
3          0.357143        0.321429                   0.142857   
4          0.285714        0.142857                   0.171429   
5          0.250000        0.416667                   0.125000   
6          0.000000        0.666667                   0.333333   
7          0.166667        0.166667                   0.166667   
8          0.000000        0.111111                   0.222222   
9          0.294118        0.264706                   0.205882   
10         0.333333        0.111111                   0.222222   
11         0.000000        0.200000                   0.500000   
12         0.000000        0.210526                   0.526316   
13         0.100000        0.100000                   0.500000   
14         0.000000        0.130435                   0.434783   
15         0.133333        0.266667                   0.333333   
16         0.200000        0.300000                   0.000000   
17         0.000000        0.363636                   0.136364   
18         0.000000        1.000000                   0.000000   

    sky_view_factor  penthouse_factor  football_field   north_o    east_o  \
0          0.136364          0.113636        0.113636  0.000000  0.000000   
1          0.179487          0.000000        0.000000  0.000000  0.000000   
2          0.142857          0.163265        0.102041  0.000000  0.102041   
3          0.178571          0.000000        0.000000  0.000000  0.000000   
4          0.114286          0.000000        0.228571  0.057143  0.000000   
5          0.083333          0.000000        0.000000  0.000000  0.000000   
6          0.000000          0.000000        0.000000  0.000000  0.000000   
7          0.166667          0.166667        0.166667  0.000000  0.000000   
8          0.333333          0.000000        0.000000  0.000000  0.000000   
9          0.147059          0.000000        0.000000  0.000000  0.000000   
10         0.000000          0.000000        0.000000  0.000000  0.000000   
11         0.150000          0.000000        0.000000  0.000000  0.000000   
12         0.000000          0.000000        0.000000  0.000000  0.000000   
13         0.050000          0.000000        0.000000  0.000000  0.250000   
14         0.000000          0.000000        0.000000  0.000000  0.217391   
15         0.166667          0.000000        0.000000  0.000000  0.000000   
16         0.200000          0.000000        0.000000  0.000000  0.000000   
17         0.363636          0.000000        0.000000  0.136364  0.000000   
18         0.000000          0.000000        0.000000  0.000000  0.000000   

     south_o    west_o  assisted_living  library  fab_labs  startups  shops  \
0   0.113636  0.113636         0.000000    0.000  0.000000  0.000000   0.00   
1   0.000000  0.000000         0.076923    0.000  0.000000  0.000000   0.00   
2   0.102041  0.000000         0.000000    0.000  0.000000  0.000000   0.00   
3   0.000000  0.000000         0.000000    0.000  0.000000  0.000000   0.00   
4   0.000000  0.000000         0.000000    0.000  0.000000  0.000000   0.00   
5   0.000000  0.000000         0.000000    0.125  0.000000  0.000000   0.00   
6   0.000000  0.000000         0.000000    0.000  0.000000  0.000000   0.00   
7   0.000000  0.000000         0.000000    0.000  0.000000  0.000000   0.00   
8   0.000000  0.000000         0.000000    0.000  0.333333  0.000000   0.00   
9   0.000000  0.000000         0.000000    0.000  0.000000  0.088235   0.00   
10  0.000000  0.000000         0.000000    0.000  0.000000  0.333333   0.00   
11  0.000000  0.000000         0.000000    0.000  0.000000  0.000000   0.15   
12  0.157895  0.105263         0.000000    0.000  0.000000  0.000000   0.00   
13  0.000000  0.000000         0.000

Load the value fields

In [6]:
# loading the lattice from csv
fields = {}
for f in program_prefs.columns:
    lattice_path = os.path.relpath('../data/fields/' + f + '.csv')
    fields[f] = tg.lattice_from_csv(lattice_path)

Initialize the agents

In [7]:
# initialize the occupation lattice
occ_lattice = avail_lattice * 0 - 1

# Finding the index of the available voxels in avail_lattice
avail_flat = avail_lattice.flatten()
avail_index = np.array(np.where(avail_lattice == 1)).T

# Randomly choosing three available voxels
agn_num = len(program_prefs)
np.random.seed()
select_id = np.random.choice(len(avail_index), agn_num)
agn_origins = avail_index[select_id]

# adding the origins to the agents locations
agn_locs = []
# for each agent origin ... 
for a_id, a_origin in enumerate(agn_origins):

    # add the origin to the list of agent locations
    agn_locs.append([a_origin])

    # set the origin in availablity lattice as 0 (UNavailable)
    avail_lattice[tuple(a_origin)] = 0

    # set the origin in occupation lattice as the agent id (a_id)
    occ_lattice[tuple(a_origin)] = a_id

printing the ammount of agents

In [8]:
print(a_id)

18


show the agents

In [9]:
p = pv.Plotter(notebook=True)

# Set the grid dimensions: shape + 1 because we want to inject our values on the CELL data
grid = pv.UniformGrid()
grid.dimensions = np.array(occ_lattice.shape) + 1
# The bottom left corner of the data set
grid.origin = occ_lattice.minbound - occ_lattice.unit * 0.5
# These are the cell sizes along each axis
grid.spacing = occ_lattice.unit 

# adding the boundingbox wireframe
p.add_mesh(grid.outline(), color="grey", label="Domain")

# adding axes
p.add_axes()
p.show_bounds(grid="back", location="back", color="#777777")

# Add the data values to the cell data
grid.cell_arrays["Agents"] = occ_lattice.flatten(order="F").astype(int)  # Flatten the array!
# filtering the voxels
threshed = grid.threshold([-0.1, agn_num - 0.9])
# adding the voxels
p.add_mesh(threshed, show_edges=True, opacity=1.0, show_scalar_bar=False)

# adding the availability lattice
# init_avail_lattice.fast_vis(p)

p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(235.5797258158867, 141.07972438537521, 217.47972465955658),
 (35.70000076293945, -58.80000066757202, 17.599999606609344),
 (0.0, 0.0, 1.0)]

Run the simulation

In [10]:
# make a deep copy of occupation lattice
cur_occ_lattice = tg.to_lattice(np.copy(occ_lattice), occ_lattice)
# initialzing the list of frames
frames = [cur_occ_lattice]

# setting the time variable to 0
t = 0
n_frames = 1000
# main feedback loop of the simulation (for each time step ...)
while t<n_frames:
    # for each agent ... 
    for a_id, a_prefs in relative_prefs_norm.iterrows():
        # retrieve the list of the locations of the current agent
        a_locs = agn_locs[a_id]
        # initialize the list of free neighbours
        free_neighs = []
        # for each location of the agent
        for loc in a_locs:
            # retrieve the list of neighbours of the agent based on the stencil
            neighs = avail_lattice.find_neighbours_masked(stencil, loc = loc)
            
            # for each neighbour ... 
            for n in neighs:
                # compute 3D index of neighbour
                neigh_3d_id = np.unravel_index(n, avail_lattice.shape)
                # if the neighbour is available... 
                if avail_lattice[neigh_3d_id]:
                    # add the neighbour to the list of free neighbours
                    free_neighs.append(neigh_3d_id)
        # check if found any free neighbour
        if len(free_neighs)>0:
            # convert free neighbours to a numpy array
            fns = np.array(free_neighs)

            # find the value of neighbours
            # init the agent value array
            a_eval = np.ones(len(fns))
            # for each field...
            for f in program_prefs.columns:
                # find the raw value of free neighbours...
                vals = fields[f][fns[:,0], fns[:,1], fns[:,2]]
                # raise the the raw value to the power of preference weight of the agent
                a_weighted_vals = vals ** a_prefs[f]
                # multiply them to the previous weighted values
                a_eval *= a_weighted_vals

            #post-processing
            functions.squareness(square_weight=0.9, free_neighs=free_neighs, a_eval=a_eval)


            # select the neighbour with highest evaluation
            selected_int = np.argmax(a_eval)
            # find 3D integer index of selected neighbour
            selected_neigh_3d_id = free_neighs[selected_int]
            # find the location of the newly selected neighbour
            selected_neigh_loc = np.array(selected_neigh_3d_id).flatten()
            # add the newly selected neighbour location to agent locations
            agn_locs[a_id].append(selected_neigh_loc)
            # set the newly selected neighbour as UNavailable (0) in the availability lattice
            avail_lattice[selected_neigh_3d_id] = 0
            # set the newly selected neighbour as OCCUPIED by current agent 
            # (-1 means not-occupied so a_id)
            occ_lattice[selected_neigh_3d_id] = a_id

    # constructing the new lattice
    new_occ_lattice = tg.to_lattice(np.copy(occ_lattice), occ_lattice)
    # adding the new lattice to the list of frames
    frames.append(new_occ_lattice)
    # adding one to the time counter
    print(t)
    t += 1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

Visualize the result

In [11]:
p = pv.Plotter(notebook=True)

base_lattice = frames[0]

# Set the grid dimensions: shape + 1 because we want to inject our values on the CELL data
grid = pv.UniformGrid()
grid.dimensions = np.array(base_lattice.shape) + 1
# The bottom left corner of the data set
grid.origin = base_lattice.minbound - base_lattice.unit * 0.5
# These are the cell sizes along each axis
grid.spacing = base_lattice.unit 

# adding the boundingbox wireframe
p.add_mesh(grid.outline(), color="grey", label="Domain")

# adding the availability lattice
init_avail_lattice.fast_vis(p)

# adding axes
p.add_axes()
p.show_bounds(grid="back", location="back", color="#aaaaaa")

def create_mesh(value):
    f = int(value)
    lattice = frames[f]

    # Add the data values to the cell data
    grid.cell_arrays["Agents"] = lattice.flatten(order="F").astype(int)  # Flatten the array!
    # filtering the voxels
    threshed = grid.threshold([-0.1, agn_num - 0.9])
    # adding the voxels
    p.add_mesh(threshed, name='sphere', show_edges=True, opacity=1.0, show_scalar_bar=False)

    return

p.add_slider_widget(create_mesh, [0, n_frames], title='Time', value=0, event_type="always", style="classic")
p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(235.5797258158867, 141.07972438537521, 217.47972465955658),
 (35.70000076293945, -58.80000066757202, 17.599999606609344),
 (0.0, 0.0, 1.0)]