A lot of this stuff hinges on having the right initial data. We cant run the agents at this moment. I Added the stuff here that was already in workshop 4, but like I said, it will not run.

Personally, I believe that we have to store the eventual data of every script in a csv file. This script needs a program of requirements.

Load Libraries

In [1]:
import os
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import pandas as pd
import numpy as np
np.random.seed(0)

Define Stencil

In [2]:
# creating neighborhood definition
stencil = tg.create_stencil("von_neumann", 1, 1)
# setting the center to zero
stencil.set_index([0,0,0], 0)
print(stencil)

[[[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 1 0]
  [1 0 1]
  [0 1 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]]


Define the environment

In [3]:
# loading the lattice from csv
lattice_path = os.path.relpath('../data/meshes/voxelized_envelope_highres.csv')
avail_lattice = tg.lattice_from_csv(lattice_path)
init_avail_lattice = tg.to_lattice(np.copy(avail_lattice), avail_lattice)

load program (insert the program of requirements here)

In [4]:
#loading the relative relations excell

# relative_rels = pd.read_excel('../data/relationships/relative_relations.xlsx', index_col=0) 
# relative_rels_norm = relative_rels.div(relative_rels.sum(axis=1), axis=0)
# relative_rels_norm = relative_rels_norm.fillna(0)

#loading the relative preferences excell
relative_prefs = pd.read_excel('../data/relationships/experimental_preferences.xlsx')
relative_prefs.iloc[:, 1:] = relative_prefs.iloc[:, 1:].div(relative_prefs.iloc[:, 1:].sum(axis=1), axis=0)
relative_prefs.iloc[:, 1:] = relative_prefs.iloc[:, 1:].fillna(0)
relative_prefs_norm = relative_prefs
relative_prefs_norm

space_name  facade_connection  sunlight_access  noise_approval  \
0    student_housing           0.181785         0.181785        0.145428   
1       co_cooking_A           0.196040         0.196040        0.098020   
2    assisted_living           0.181752         0.181752        0.163577   
3       co_cooking_B           0.192234         0.192234        0.134564   
4    starter_housing           0.172384         0.172384        0.155146   
5       co_cooking_C           0.181785         0.181785        0.127250   
6         co_working           0.184162         0.263089        0.236780   
7   community_center           0.131510         0.263019        0.131510   
8            library           0.115252         0.230503        0.384172   
9       cinematheque           0.074074         0.074074        0.370370   
10           laundry           0.125000         0.125000        0.125000   
11          fab_labs           0.001653         0.495868        0.165289   
12          startups           0.243724         0.243724        0.219352   
13          workshop           0.331858         0.331858        0.110619   
14             shops           0.344471         0.000344        0.137788   
15           grocery           0.000711         0.000711        0.284495   
16               gym           0.099900         0.099900        0.099900   
17        drug_store           0.000766         0.000766        0.229709   
18        restaurant           0.093691         0.124922        0.249844   
19        vegetation           0.000993         0.000993        0.000993   
20             lobby           0.262743         0.105097        0.157646   
21   communal_garden           0.000712         0.000712        0.355872   
22            arcade           0.002457         0.002457        0.982801   

    proximity_to_ground_floor  sky_view_factor  penthouse_factor  \
0                    0.000182         0.109071          0.090893   
1                    0.000196         0.117624          0.098020   
2                    0.181752         0.127226          0.000182   
3                    0.192234         0.134564          0.000192   
4                    0.000172         0.120669          0.137907   
5                    0.000182         0.127250          0.145428   
6                    0.105235         0.131544          0.000263   
7                    0.157812         0.105208          0.000263   
8                    0.192086         0.076834          0.000384   
9                    0.185185         0.074074          0.074074   
10                   0.125000         0.125000          0.125000   
11                   0.330579         0.001653          0.001653   
12                   0.170607         0.121862          0.000244   
13                   0.221239         0.001106          0.001106   
14                   0.344471         0.103341          0.000344   
15                   0.711238         0.000711          0.000711   
16                   0.499500         0.049950          0.000500   
17                   0.765697         0.000766          0.000766   
18                   0.312305         0.156152          0.000312   
19                   0.993049         0.000993          0.000993   
20                   0.000525         0.105097          0.000525   
21                   0.000712         0.569395          0.000712   
22                   0.002457         0.002457          0.002457   

    street_sight  football_field  
0       0.163607        0.127250  
1       0.156832        0.137228  
2       0.163577        0.000182  
3       0.153787        0.000192  
4       0.155146        0.086192  
5       0.145428        0.090893  
6       0.078927        0.000000  
7       0.000263        0.210416  
8       0.000384        0.000384  
9       0.074074        0.074074  
10      0.125000        0.125000  
11      0.001653        0.001653  
12      0.000244        0.000244  
13      0.001106        0.001106  
14      0.068894        0.0

In [5]:
program_prefs = relative_prefs_norm.drop(["space_name", "facade_connection","penthouse_factor","street_sight"], 1)
program_prefs

sunlight_access  noise_approval  proximity_to_ground_floor  \
0          0.181785        0.145428                   0.000182   
1          0.196040        0.098020                   0.000196   
2          0.181752        0.163577                   0.181752   
3          0.192234        0.134564                   0.192234   
4          0.172384        0.155146                   0.000172   
5          0.181785        0.127250                   0.000182   
6          0.263089        0.236780                   0.105235   
7          0.263019        0.131510                   0.157812   
8          0.230503        0.384172                   0.192086   
9          0.074074        0.370370                   0.185185   
10         0.125000        0.125000                   0.125000   
11         0.495868        0.165289                   0.330579   
12         0.243724        0.219352                   0.170607   
13         0.331858        0.110619                   0.221239   
14         0.000344        0.137788                   0.344471   
15         0.000711        0.284495                   0.711238   
16         0.099900        0.099900                   0.499500   
17         0.000766        0.229709                   0.765697   
18         0.124922        0.249844                   0.312305   
19         0.000993        0.000993                   0.993049   
20         0.105097        0.157646                   0.000525   
21         0.000712        0.355872                   0.000712   
22         0.002457        0.982801                   0.002457   

    sky_view_factor  football_field  
0          0.109071        0.127250  
1          0.117624        0.137228  
2          0.127226        0.000182  
3          0.134564        0.000192  
4          0.120669        0.086192  
5          0.127250        0.090893  
6          0.131544        0.000000  
7          0.105208        0.210416  
8          0.076834        0.000384  
9          0.074074        0.074074  
10         0.125000        0.125000  
11         0.001653        0.001653  
12         0.121862        0.000244  
13         0.001106        0.001106  
14         0.103341        0.000344  
15         0.000711        0.000711  
16         0.049950        0.000500  
17         0.000766        0.000766  
18         0.156152        0.000312  
19         0.000993        0.000993  
20         0.105097        0.000525  
21         0.569395        0.000712  
22         0.002457        0.002457

Load the value fields

In [6]:
# loading the lattice from csv
fields = {}
for f in program_prefs.columns:
    lattice_path = os.path.relpath('../data/fields/' + f + '.csv')
    fields[f] = tg.lattice_from_csv(lattice_path)

Load the initial condition feed

In [7]:
agent_pref_fields=[]
for i in range(0,len(program_prefs)):
    int=1
    for f in program_prefs:
        t=fields[f]**program_prefs[f][i]
        int=int*t
    agent_pref_fields.append(int)


In [8]:
# jk=24
# kj=15
# apple=0
# tryt=fields["noise_approval"]**program_prefs["noise_approval"][apple]
# print(fields["noise_approval"][jk,kj])
# print(tryt[jk,kj])

In [9]:
# program_prefs["noise_approval"][apple]

In [10]:
# coby0=fields["sunlight_access"]**program_prefs["sunlight_access"][apple]
# coby1=fields["noise_approval"]**program_prefs["noise_approval"][apple]
# coby2=fields["proximity_to_ground_floor"]**program_prefs["proximity_to_ground_floor"][apple]
# coby3=fields["sky_view_factor"]**program_prefs["sky_view_factor"][apple]
# coby4=fields["football_field"]**program_prefs["football_field"][apple]
# coby5=coby0[jk,kj]*coby1[jk,kj]*coby2[jk,kj]*coby3[jk,kj]*coby4[jk,kj]
# print(coby5)


In [11]:
# alala=(fields["noise_approval"]**program_prefs["noise_approval"][apple])*(fields["sunlight_access"]**program_prefs["sunlight_access"][apple])*(fields["proximity_to_ground_floor"]**program_prefs["proximity_to_ground_floor"][apple])*(fields["sky_view_factor"]**program_prefs["sky_view_factor"][apple])*(fields["football_field"]**program_prefs["football_field"][apple])
# print(alala[jk,kj])
# print(agent_pref_fields[apple][jk,kj])

In [12]:
# alala=(fields["noise_approval"]**program_prefs["noise_approval"][apple])*(fields["sunlight_access"]**program_prefs["sunlight_access"][apple])*(fields["proximity_to_ground_floor"]**program_prefs["proximity_to_ground_floor"][apple])*(fields["sky_view_factor"]**program_prefs["sky_view_factor"][apple])*(fields["football_field"]**program_prefs["football_field"][apple])
# alala_flat=alala.flatten()
# best_index = np.array(np.where(alala == alala.max())).T
# print(best_index)

In [13]:
int_cond_fields=[]
for i in range(0,len(program_prefs)):
    int_cond_field=(fields["noise_approval"]**program_prefs["noise_approval"][i])*(fields["sunlight_access"]**program_prefs["sunlight_access"][i])*(fields["proximity_to_ground_floor"]**program_prefs["proximity_to_ground_floor"][i])*(fields["sky_view_factor"]**program_prefs["sky_view_factor"][i])*(fields["football_field"]**program_prefs["football_field"][i])
    int_cond_fields.append(int_cond_field)

In [14]:
for i in range(0,len(program_prefs)):
    agn_locs=[]
    best_index = np.array(np.where(int_cond_fields[i] == int_cond_fields[i].max())).T
    agn_locs.append(best_index)
    for j in range(i,len(program_prefs)):
        int_cond_fields[j][tuple(best_index)] = 0
print(agn_locs)
    
    

IndexError: index 18 is out of bounds for axis 2 with size 8

array([[10,  4,  2],
       [15,  4,  2],
       [18,  4,  2]], dtype=int64)

In [20]:
occ_lattice = avail_lattice * 0 - 1
avail_index = np.array(np.where(avail_lattice == 1)).T
agn_num=len(program_prefs)
agn_origins=[]
for i in range(0,agn_num):
    best_index = np.array(np.where(int_cond_fields[i] == int_cond_fields[i].max())).T
    best_index=best_index[0]
    agn_origins.append(best_index)

In [21]:
agn_origins

[array([ 7, 16,  6], dtype=int64),
 array([9, 8, 6], dtype=int64),
 array([26, 12,  2], dtype=int64),
 array([24, 12,  2], dtype=int64),
 array([ 5, 14,  6], dtype=int64),
 array([9, 8, 6], dtype=int64),
 array([ 3, 14,  4], dtype=int64),
 array([22, 14,  2], dtype=int64),
 array([22,  5,  2], dtype=int64),
 array([10,  4,  2], dtype=int64),
 array([10,  5,  2], dtype=int64),
 array([29, 15,  2], dtype=int64),
 array([10,  4,  2], dtype=int64),
 array([29, 15,  2], dtype=int64),
 array([20,  4,  1], dtype=int64),
 array([18,  4,  1], dtype=int64),
 array([18,  4,  1], dtype=int64),
 array([18,  4,  1], dtype=int64),
 array([10,  4,  2], dtype=int64),
 array([10,  5,  1], dtype=int64),
 array([9, 4, 6], dtype=int64),
 array([9, 4, 6], dtype=int64),
 array([9, 4, 6], dtype=int64)]

In [ ]:
int_cond_fields[j][tuple(best_index)]=0

visualizing starting condition per agent. 

In [27]:
# i represents the specific agent being looked at
i=apple

l=agent_pref_fields[i]
# initiating the plotter
p = pv.Plotter()

# Create the spatial reference
grid = pv.UniformGrid()

# Set the grid dimensions: shape because we want to inject our values
grid.dimensions = l.shape
# The bottom left corner of the data set
grid.origin = l.minbound
# These are the cell sizes along each axis
grid.spacing = l.unit

# Add the data values to the cell data
grid.point_arrays["Distance"] = l.flatten(order="F")  # Flatten the Lattice

# adding the meshes
# p.add_mesh(tri_to_pv(context_mesh), opacity=0.1, style='wireframe')

# adding the volume
opacity = np.array([0,0.6,0.6,0.6,0.6,0.6,0.6]) * 1.5
p.add_volume(grid, cmap="coolwarm", opacity=opacity, shade=True, show_scalar_bar=False)

# plotting
p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(231.22009113429812, 138.72009113429812, 213.72009113429812),
 (35.0, -57.5, 17.5),
 (0.0, 0.0, 1.0)]

In [35]:
voxel_index=np.where(agent_pref_fields[0]==agent_pref_fields[0].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])

[[ 8]
 [16]
 [ 6]]


In [16]:
voxel_index=np.where(agent_pref_fields[0]==agent_pref_fields[0].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[1]==agent_pref_fields[1].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[2]==agent_pref_fields[2].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[3]==agent_pref_fields[3].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[4]==agent_pref_fields[4].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[5]==agent_pref_fields[5].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[6]==agent_pref_fields[6].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[7]==agent_pref_fields[7].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[8]==agent_pref_fields[8].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[9]==agent_pref_fields[9].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[10]==agent_pref_fields[10].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[11]==agent_pref_fields[11].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[12]==agent_pref_fields[12].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[13]==agent_pref_fields[13].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[14]==agent_pref_fields[14].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[15]==agent_pref_fields[15].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[16]==agent_pref_fields[16].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[17]==agent_pref_fields[17].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[18]==agent_pref_fields[18].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[19]==agent_pref_fields[19].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[20]==agent_pref_fields[20].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[21]==agent_pref_fields[21].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[22]==agent_pref_fields[22].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[23]==agent_pref_fields[23].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step
voxel_index=np.where(agent_pref_fields[24]==agent_pref_fields[24].max())
print(voxel_index[0],voxel_index[1],voxel_index[2])
#new step

[8] [16] [6]
[8] [16] [6]
[25] [11] [2]
[25] [12] [2]
[8] [16] [6]
[8] [16] [6]
[25] [11] [3]
[4] [14] [2]
[25] [6] [2]
[25] [6] [2]
[25] [11] [2]
[25] [12] [2]
[25] [12] [2]
[25] [12] [2]
[25] [11] [1]
[25] [11] [1]
[25] [6] [1]
[25] [6] [1]
[25] [11] [1]
[25] [6] [1]
[25] [6] [2]
[25] [11] [1]
[25] [6] [6]
[25] [6] [6]
[25] [6] [6]


Finding best voxel for that agent

In [17]:
i=19
# removing values above set threshold and setting them to zero
new_agent_pref_field = np.where(agent_pref_fields[i] != agent_pref_fields[i].max(),0,agent_pref_fields[i])

# set all usable values to 1

pref_lattice = np.where(new_agent_pref_field > 0, 1,new_agent_pref_field)
pref_lattice = pref_lattice.astype(bool)
pref_lattice = tg.to_lattice(pref_lattice, agent_pref_fields[i])
pref_lattice.shape

# initiating the plotter
p = pv.Plotter()

# fast visualization of the lattice
pref_lattice.fast_vis(p)

# # adding the meshes
# p.add_mesh(tri_to_pv(context_mesh), color='#aaaaaa')

# plotting
p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(239.8279062084888, 147.3279062084888, 222.3279062084888),
 (35.0, -57.5, 17.5),
 (0.0, 0.0, 1.0)]

Initialize the agents

In [13]:
# initialize the occupation lattice
occ_lattice = avail_lattice * 0 - 1

# Finding the index of the available voxels in avail_lattice
avail_flat = avail_lattice.flatten()
avail_index = np.array(np.where(avail_lattice == 1)).T

# Randomly choosing three available voxels
agn_num = len(program_prefs)
select_id = np.random.choice(len(avail_index), agn_num)
agn_origins = avail_index[select_id]

# adding the origins to the agents locations
agn_locs = []
# for each agent origin ... 
for a_id, a_origin in enumerate(agn_origins):

    # add the origin to the list of agent locations
    agn_locs.append([a_origin])

    # set the origin in availablity lattice as 0 (UNavailable)
    avail_lattice[tuple(a_origin)] = 0

    # set the origin in occupation lattice as the agent id (a_id)
    occ_lattice[tuple(a_origin)] = a_id

printing the ammount of agents

In [14]:
print(a_id)

24


show the agents

In [15]:
p = pv.Plotter(notebook=True)

# Set the grid dimensions: shape + 1 because we want to inject our values on the CELL data
grid = pv.UniformGrid()
grid.dimensions = np.array(occ_lattice.shape) + 1
# The bottom left corner of the data set
grid.origin = occ_lattice.minbound - occ_lattice.unit * 0.5
# These are the cell sizes along each axis
grid.spacing = occ_lattice.unit 

# adding the boundingbox wireframe
p.add_mesh(grid.outline(), color="grey", label="Domain")

# adding axes
p.add_axes()
p.show_bounds(grid="back", location="back", color="#777777")

# Add the data values to the cell data
grid.cell_arrays["Agents"] = occ_lattice.flatten(order="F").astype(int)  # Flatten the array!
# filtering the voxels
threshed = grid.threshold([-0.1, agn_num - 0.9])
# adding the voxels
p.add_mesh(threshed, show_edges=True, opacity=1.0, show_scalar_bar=False)

# adding the availability lattice
init_avail_lattice.fast_vis(p)

p.show(use_ipyvtk=True)

TypeError: Cannot construct a dtype from an array

Run the simulation

In [21]:
# make a deep copy of occupation lattice
cur_occ_lattice = tg.to_lattice(np.copy(occ_lattice), occ_lattice)
# initialzing the list of frames
frames = [cur_occ_lattice]

# setting the time variable to 0
t = 0
n_frames = 30
# main feedback loop of the simulation (for each time step ...)
while t<n_frames:
    # for each agent ... 
    for a_id, a_prefs in relative_prefs_norm.iterrows():
        # retrieve the list of the locations of the current agent
        a_locs = agn_locs[a_id]
        # initialize the list of free neighbours
        free_neighs = []
        # for each location of the agent
        for loc in a_locs:
            # retrieve the list of neighbours of the agent based on the stencil
            neighs = avail_lattice.find_neighbours_masked(stencil, loc = loc)
            
            # for each neighbour ... 
            for n in neighs:
                # compute 3D index of neighbour
                neigh_3d_id = np.unravel_index(n, avail_lattice.shape)
                # if the neighbour is available... 
                if avail_lattice[neigh_3d_id]:
                    # add the neighbour to the list of free neighbours
                    free_neighs.append(neigh_3d_id)
        # check if found any free neighbour
        if len(free_neighs)>0:
            # convert free neighbours to a numpy array
            fns = np.array(free_neighs)

            # find the value of neighbours
            # init the agent value array
            a_eval = np.ones(len(fns))
            # for each field...
            for f in program_prefs.columns:
                # find the raw value of free neighbours...
                vals = fields[f][fns[:,0], fns[:,1], fns[:,2]]
                # raise the the raw value to the power of preference weight of the agent
                a_weighted_vals = vals ** a_prefs[f]
                # multiply them to the previous weighted values
                a_eval *= a_weighted_vals

            # select the neighbour with highest evaluation
            selected_int = np.argmax(a_eval)
            # find 3D integer index of selected neighbour
            selected_neigh_3d_id = free_neighs[selected_int]
            # find the location of the newly selected neighbour
            selected_neigh_loc = np.array(selected_neigh_3d_id).flatten()
            # add the newly selected neighbour location to agent locations
            agn_locs[a_id].append(selected_neigh_loc)
            # set the newly selected neighbour as UNavailable (0) in the availability lattice
            avail_lattice[selected_neigh_3d_id] = 0
            # set the newly selected neighbour as OCCUPIED by current agent 
            # (-1 means not-occupied so a_id)
            occ_lattice[selected_neigh_3d_id] = a_id

    # constructing the new lattice
    new_occ_lattice = tg.to_lattice(np.copy(occ_lattice), occ_lattice)
    # adding the new lattice to the list of frames
    frames.append(new_occ_lattice)
    # adding one to the time counter
    t += 1

Visualize the result

In [22]:
p = pv.Plotter(notebook=True)

base_lattice = frames[0]

# Set the grid dimensions: shape + 1 because we want to inject our values on the CELL data
grid = pv.UniformGrid()
grid.dimensions = np.array(base_lattice.shape) + 1
# The bottom left corner of the data set
grid.origin = base_lattice.minbound - base_lattice.unit * 0.5
# These are the cell sizes along each axis
grid.spacing = base_lattice.unit 

# adding the boundingbox wireframe
p.add_mesh(grid.outline(), color="grey", label="Domain")

# adding the availability lattice
init_avail_lattice.fast_vis(p)

# adding axes
p.add_axes()
p.show_bounds(grid="back", location="back", color="#aaaaaa")

def create_mesh(value):
    f = int(value)
    lattice = frames[f]

    # Add the data values to the cell data
    grid.cell_arrays["Agents"] = lattice.flatten(order="F").astype(int)  # Flatten the array!
    # filtering the voxels
    threshed = grid.threshold([-0.1, agn_num - 0.9])
    # adding the voxels
    p.add_mesh(threshed, name='sphere', show_edges=True, opacity=1.0, show_scalar_bar=False)

    return

p.add_slider_widget(create_mesh, [0, n_frames], title='Time', value=0, event_type="always", style="classic")
p.show(use_ipyvtk=True)

ViewInteractiveWidget(height=768, layout=Layout(height='auto', width='100%'), width=1024)

[(239.8279062084888, 147.3279062084888, 222.3279062084888),
 (35.0, -57.5, 17.5),
 (0.0, 0.0, 1.0)]